// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14Si2-E_HoFJc9eC0dZIQKdVTd8QyiDQ',
    appId: '1:325266960696:web:950e719e778dc5cc8151cd',
    messagingSenderId: '325266960696',
    projectId: 'app-calculadora-9add9',
    authDomain: 'app-calculadora-9add9.firebaseapp.com',
    storageBucket: 'app-calculadora-9add9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRwWEywTK94WjmaGhXyNGCOFpQ9OxKSfg',
    appId: '1:325266960696:android:179779fc38f307488151cd',
    messagingSenderId: '325266960696',
    projectId: 'app-calculadora-9add9',
    storageBucket: 'app-calculadora-9add9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF1TlpxjjuvTz607aDypdrk-huLOtfMWM',
    appId: '1:325266960696:ios:2b3a68435445b60f8151cd',
    messagingSenderId: '325266960696',
    projectId: 'app-calculadora-9add9',
    storageBucket: 'app-calculadora-9add9.firebasestorage.app',
    iosBundleId: 'com.example.aula11Calc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF1TlpxjjuvTz607aDypdrk-huLOtfMWM',
    appId: '1:325266960696:ios:2b3a68435445b60f8151cd',
    messagingSenderId: '325266960696',
    projectId: 'app-calculadora-9add9',
    storageBucket: 'app-calculadora-9add9.firebasestorage.app',
    iosBundleId: 'com.example.aula11Calc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD14Si2-E_HoFJc9eC0dZIQKdVTd8QyiDQ',
    appId: '1:325266960696:web:75f251ce8b024ff58151cd',
    messagingSenderId: '325266960696',
    projectId: 'app-calculadora-9add9',
    authDomain: 'app-calculadora-9add9.firebaseapp.com',
    storageBucket: 'app-calculadora-9add9.firebasestorage.app',
  );
}
